#!/bin/bash
# This script is called by `ccex`
#
# [EXPORTED VARIABLES]
# - CCEX_PROJECT_PATH
#
# [WHAT IT DOES]
# - Do formatting

CCEX_STYLE_PATH="${CCEX_PROJECT_PATH}/infra/style"

source ${CCEX_STYLE_PATH}/format.sh "$@"
