#!/bin/bash
# This script is called by `ccex`
#
# [EXPORTED VARIABLES]
# - CCEX_PROJECT_PATH
#
# [WHAT IT DOES]
# - Install built `tico` package
# - Install runtime dependencies

CCEX_SCRIPTS_PATH="${CCEX_PROJECT_PATH}/infra/scripts"

source ${CCEX_SCRIPTS_PATH}/install.sh "$@"
