#!/bin/bash
# This script is called by `ccex`
#
# [EXPORTED VARIABLES]
# - CCEX_PROJECT_PATH
#
# [WHAT IT DOES]
# - Run test

CCEX_SCRIPTS_PATH="${CCEX_PROJECT_PATH}/infra/scripts"

python3 ${CCEX_SCRIPTS_PATH}/test_run.py "$@"
